import { FACE_PROFILE, hairRenderState, scalpSample } from './assets-core-v5.js';

function orient(THREE,matrix,position,normal,scale,twist=0){const up=new THREE.Vector3(0,1,0),q=new THREE.Quaternion().setFromUnitVectors(up,normal.clone().normalize());if(twist)q.multiply(new THREE.Quaternion().setFromAxisAngle(normal,twist));matrix.compose(position,q,scale)}
function capsule(THREE,r,l,m){return new THREE.Mesh(new THREE.CapsuleGeometry(r,l,6,10),m)}
function eye(THREE,m,side){const g=new THREE.Group(),white=new THREE.Mesh(new THREE.SphereGeometry(.18,18,12),m.eyeWhite);white.scale.set(1.28,.56,.48);const iris=new THREE.Mesh(new THREE.SphereGeometry(.078,14,10),m.iris);iris.position.z=.158;const pupil=new THREE.Mesh(new THREE.SphereGeometry(.035,10,8),m.pupil);pupil.position.z=.222;const light=new THREE.Mesh(new THREE.SphereGeometry(.014,8,6),m.catchlight);light.position.set(side*-.018,.025,.252);g.add(white,iris,pupil,light);return g}
function sideHair(THREE,material){const geo=new THREE.ConeGeometry(.032,.18,5);geo.translate(0,.09,0);const mesh=new THREE.InstancedMesh(geo,material,FACE_PROFILE.sideHairDensity),matrix=new THREE.Matrix4();let cursor=0;for(let ring=0;ring<5;ring++){const theta=.78+ring*.13,per=ring===4?24:17;for(let i=0;i<per&&cursor<FACE_PROFILE.sideHairDensity;i++){const phi=-2.62+i/Math.max(1,per-1)*5.24;if(Math.sin(phi)>.64&&theta<1.12)continue;const normal=new THREE.Vector3(Math.sin(theta)*Math.cos(phi),Math.cos(theta),Math.sin(theta)*Math.sin(phi)),pos=normal.clone().multiply(new THREE.Vector3(1.09,1.28,1.05));orient(THREE,matrix,pos,normal,new THREE.Vector3(.76,.72+ring*.03,.76),phi*.06);mesh.setMatrixAt(cursor++,matrix)}}mesh.count=cursor;return mesh}

export function createVincentModel(THREE,{qualityFactor=1}={}){
 const m={skin:new THREE.MeshPhysicalMaterial({color:0xb96f49,roughness:.42,clearcoat:.25,clearcoatRoughness:.28}),skinWarm:new THREE.MeshStandardMaterial({color:0xa85a3c,roughness:.5}),shirt:new THREE.MeshPhysicalMaterial({color:0xf1eee6,roughness:.58}),shirtShadow:new THREE.MeshStandardMaterial({color:0xcac7c0,roughness:.7}),hair:new THREE.MeshPhysicalMaterial({color:0x25130f,roughness:.48,clearcoat:.08,clearcoatRoughness:.3}),beard:new THREE.MeshStandardMaterial({color:0x2b1712,roughness:.72}),eyeWhite:new THREE.MeshStandardMaterial({color:0xfff7eb,roughness:.35}),iris:new THREE.MeshPhysicalMaterial({color:0x4b2a19,roughness:.18,clearcoat:.55}),pupil:new THREE.MeshBasicMaterial({color:0x090304}),catchlight:new THREE.MeshBasicMaterial({color:0xffffff}),lip:new THREE.MeshStandardMaterial({color:0x7d3f36,roughness:.55}),gold:new THREE.MeshPhysicalMaterial({color:0xffd166,roughness:.24,metalness:.8})};
 const root=new THREE.Group(),torso=new THREE.Mesh(new THREE.CylinderGeometry(.78,1.12,2.25,18),m.shirt);torso.position.y=1.05;torso.castShadow=true;root.add(torso);for(const side of[-1,1]){const collar=new THREE.Mesh(new THREE.BoxGeometry(.5,.92,.12),m.shirtShadow);collar.position.set(side*.28,1.72,.78);collar.rotation.z=side*.55;collar.rotation.x=-.18;root.add(collar)}const belt=new THREE.Mesh(new THREE.TorusGeometry(.77,.09,8,30),m.gold);belt.rotation.x=Math.PI/2;belt.position.y=1.35;root.add(belt);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.35,.43,.55,16),m.skinWarm);neck.position.y=2.36;root.add(neck);
 const faceRoot=new THREE.Group();root.add(faceRoot);const cranium=new THREE.Mesh(new THREE.SphereGeometry(1.18,42,32),m.skin);cranium.scale.set(...FACE_PROFILE.cranium);cranium.position.set(0,3.64,-.02);cranium.castShadow=true;faceRoot.add(cranium);const lower=new THREE.Mesh(new THREE.SphereGeometry(1,36,28),m.skin);lower.scale.set(...FACE_PROFILE.jaw);lower.position.set(0,3.02,.11);faceRoot.add(lower);const chin=new THREE.Mesh(new THREE.SphereGeometry(.35,20,14),m.skinWarm);chin.scale.set(1,.68,.9);chin.position.set(0,2.58,.67);faceRoot.add(chin);
 for(const side of[-1,1]){const cheek=new THREE.Mesh(new THREE.SphereGeometry(.4,20,16),m.skin);cheek.scale.set(.72,.82,.44);cheek.position.set(side*.57,3.08,.72);faceRoot.add(cheek);const ear=new THREE.Mesh(new THREE.TorusGeometry(.23,.075,8,24),m.skin);ear.scale.set(FACE_PROFILE.earScale[0]*side,FACE_PROFILE.earScale[1],FACE_PROFILE.earScale[2]);ear.rotation.y=Math.PI/2;ear.position.set(side*1.09,3.36,-.02);faceRoot.add(ear);const e=eye(THREE,m,side);e.position.set(side*FACE_PROFILE.eyeSpacing,3.42,1.02);faceRoot.add(e);const brow=capsule(THREE,.045,.38,m.hair);brow.rotation.z=Math.PI/2+side*FACE_PROFILE.browAngle;brow.position.set(side*.41,3.68,1.02);faceRoot.add(brow)}
 const bridge=capsule(THREE,.105,FACE_PROFILE.noseLength,m.skin);bridge.rotation.x=Math.PI/2;bridge.position.set(0,3.24,1.08);const tip=new THREE.Mesh(new THREE.SphereGeometry(.2,20,14),m.skin);tip.scale.set(1.12,.86,1.05);tip.position.set(0,3.05,1.27);faceRoot.add(bridge,tip);for(const side of[-1,1]){const wing=new THREE.Mesh(new THREE.SphereGeometry(.09,14,10),m.skinWarm);wing.position.set(side*.15,3.03,1.22);wing.scale.set(1.1,.7,.8);faceRoot.add(wing)}const upper=capsule(THREE,.035,.34,m.lip);upper.rotation.z=Math.PI/2;upper.position.set(0,2.82,1.02);const lowerLip=upper.clone();lowerLip.position.y=2.75;lowerLip.scale.set(.88,.9,.75);faceRoot.add(upper,lowerLip);
 for(const side of[-1,1]){const moustache=new THREE.Mesh(new THREE.ConeGeometry(.09,FACE_PROFILE.moustacheWidth,8),m.beard);moustache.rotation.z=side*-1.18;moustache.position.set(side*.16,2.89,1.08);faceRoot.add(moustache)}const goatee=new THREE.Mesh(new THREE.ConeGeometry(.17,FACE_PROFILE.goateeLength,10),m.beard);goatee.position.set(0,2.43,.78);faceRoot.add(goatee);
 const scalp=new THREE.Group();scalp.position.set(0,3.7,-.02);faceRoot.add(scalp);scalp.add(sideHair(THREE,m.hair));const maxStrands=Math.max(120,Math.round(FACE_PROFILE.regrowthDensity*qualityFactor)),maxHero=Math.max(20,Math.round(FACE_PROFILE.heroLockCount*qualityFactor)),strandGeo=new THREE.ConeGeometry(.038,1,5),heroGeo=new THREE.ConeGeometry(.085,1,7);strandGeo.translate(0,.5,0);heroGeo.translate(0,.5,0);const strands=new THREE.InstancedMesh(strandGeo,m.hair,maxStrands),hero=new THREE.InstancedMesh(heroGeo,m.hair,maxHero);strands.instanceMatrix.setUsage(THREE.DynamicDrawUsage);hero.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scalp.add(strands,hero);const aura=new THREE.Mesh(new THREE.TorusGeometry(1.65,.055,8,72),new THREE.MeshBasicMaterial({color:0x5cf4ff,transparent:true,opacity:.42,blending:THREE.AdditiveBlending}));aura.rotation.x=Math.PI/2;aura.position.y=.08;root.add(aura);const glow=new THREE.PointLight(0xffc879,8,7,2);glow.position.set(0,4.35,.35);root.add(glow);
 const matrix=new THREE.Matrix4(),normal=new THREE.Vector3(),position=new THREE.Vector3(),scale=new THREE.Vector3();function updateHair(progress){const v=hairRenderState(progress),count=Math.min(maxStrands,Math.round(v.strands*qualityFactor));strands.count=count;for(let i=0;i<count;i++){const s=scalpSample(i,maxStrands),{theta,phi}=s;normal.set(Math.sin(theta)*Math.cos(phi),Math.cos(theta),Math.sin(theta)*Math.sin(phi));position.set(normal.x*1.05,normal.y*1.24,normal.z);const local=Math.max(.18,Math.min(1,v.progress*1.4-i/maxStrands*.35)),length=v.length*(.62+((i*37)%19)/40)*local;scale.set(.82+local*.25,length,.82+local*.25);const dir=normal.clone();dir.z-=v.sweep*(.18+Math.sin(phi)*.08);orient(THREE,matrix,position,dir,scale,phi*.06);strands.setMatrixAt(i,matrix)}strands.instanceMatrix.needsUpdate=true;const hc=Math.min(maxHero,Math.round(v.heroLocks*qualityFactor));hero.count=hc;for(let i=0;i<hc;i++){const phi=i/Math.max(1,hc)*Math.PI*2,theta=.22+i%5*.13;normal.set(Math.sin(theta)*Math.cos(phi),Math.cos(theta),Math.sin(theta)*Math.sin(phi));position.set(normal.x*1.02,normal.y*1.22,normal.z*.98);scale.set(.88,v.length*(1.1+i%4*.12),.88);const dir=normal.clone();dir.z-=v.sweep*.42;dir.x+=Math.sin(phi*2)*v.sweep*.12;orient(THREE,matrix,position,dir,scale,phi*.12);hero.setMatrixAt(i,matrix)}hero.instanceMatrix.needsUpdate=true;m.hair.clearcoat=v.gloss;m.skin.clearcoat=.3-v.progress*.08;glow.intensity=8+(1-v.progress)*7}
 function animate(time,movement=0){aura.rotation.z=time*1.7;aura.material.opacity=.35+Math.sin(time*4.5)*.09;faceRoot.rotation.z=Math.sin(time*2.2)*.012*movement}
 updateHair(0);return{root,faceRoot,head:cranium,materials:m,updateHair,animate}
}
