import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.min.js';
import { clamp, hairStage, tuftCountForHair, applyDamage, applyKill, consumeBankai } from './game-core.js';
const $=s=>document.querySelector(s),app=$('#app'),hud=$('#hud'),start=$('#start'),over=$('#gameover'),scoreEl=$('#score'),waveEl=$('#wave'),comboEl=$('#combo'),hpFill=$('#hpFill'),hairFill=$('#hairFill'),hpText=$('#hpText'),hairText=$('#hairText'),hairStageEl=$('#hairStage'),announceEl=$('#announcement'),flash=$('#flash'),startBtn=$('#startBtn'),restartBtn=$('#restartBtn'),loadingError=$('#loadingError');
let scene,camera,renderer,clock,player,head,hairRoot,aura,raycaster,groundPlane,enemies=[],beams=[],particles=[],projectiles=[],running=false,paused=false,lastFire=0,spawnTimer=0,msgTimer=0,shake=0,audioCtx=null;
const input={keys:{},mouse:false,pointer:new THREE.Vector2(),aim:new THREE.Vector3(0,0,-8),touchMove:new THREE.Vector2(),touchFire:false};
let state={score:0,hp:100,hair:0,wave:1,combo:1,comboTimer:0,elapsed:0,dashCd:0,invuln:0,boss:false};
const mats={skin:new THREE.MeshStandardMaterial({color:0xffb17b,roughness:.18,metalness:.28}),dark:new THREE.MeshStandardMaterial({color:0x17051f,roughness:.55,metalness:.25}),pink:new THREE.MeshStandardMaterial({color:0xff4fb3,emissive:0x6a0b48,emissiveIntensity:1.1,roughness:.28,metalness:.35}),cyan:new THREE.MeshStandardMaterial({color:0x5cf4ff,emissive:0x145d70,emissiveIntensity:1.35,roughness:.2,metalness:.5}),gold:new THREE.MeshStandardMaterial({color:0xffd166,emissive:0x7e4a08,emissiveIntensity:.65,roughness:.24,metalness:.8}),hair:new THREE.MeshStandardMaterial({color:0x2a0712,roughness:.88,metalness:.04})};
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x08010e);scene.fog=new THREE.FogExp2(0x13031e,.025);camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,150);camera.position.set(0,20,19);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;app.appendChild(renderer.domElement);clock=new THREE.Clock();raycaster=new THREE.Raycaster();groundPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);scene.add(new THREE.HemisphereLight(0x9ceaff,0x290326,1.9));const key=new THREE.DirectionalLight(0xffd8a8,3);key.position.set(-8,18,10);key.castShadow=true;scene.add(key);const rim=new THREE.PointLight(0xff30a8,42,38,2);rim.position.set(10,8,-10);scene.add(rim);buildWorld();buildPlayer();bind();updateHUD();animate()}
function buildWorld(){const ground=new THREE.Mesh(new THREE.CircleGeometry(21,72),new THREE.MeshStandardMaterial({color:0x16051e,roughness:.72,metalness:.2}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);for(let r=4;r<=20;r+=4){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.04,6,96),new THREE.MeshBasicMaterial({color:r%8===0?0xff4fb3:0x5cf4ff,transparent:true,opacity:.28}));ring.rotation.x=Math.PI/2;ring.position.y=.04;scene.add(ring)}for(const [x,z,s] of[[-13,-8,1.35],[13,7,1.1],[0,-18,1.65]])torii(x,z,s);const moon=new THREE.Mesh(new THREE.SphereGeometry(6,32,24),new THREE.MeshBasicMaterial({color:0xffefb2}));moon.position.set(-24,25,-55);scene.add(moon);for(let i=0;i<42;i++){const a=Math.random()*Math.PI*2,r=28+Math.random()*20,w=2+Math.random()*3,h=4+Math.random()*15,b=new THREE.Mesh(new THREE.BoxGeometry(w,h,w),new THREE.MeshStandardMaterial({color:[0x240632,0x0b1734,0x23103d][i%3],roughness:.8}));b.position.set(Math.cos(a)*r,h/2-1,Math.sin(a)*r);scene.add(b)}}
function torii(x,z,s){const g=new THREE.Group(),red=new THREE.MeshStandardMaterial({color:0xd6193f,emissive:0x41000e,emissiveIntensity:.4});for(const px of[-2,2]){const p=new THREE.Mesh(new THREE.BoxGeometry(.7,6,.7),red);p.position.set(px,3,0);g.add(p)}const t=new THREE.Mesh(new THREE.BoxGeometry(6,.6,.9),red);t.position.y=6;const roof=new THREE.Mesh(new THREE.BoxGeometry(7,.35,1.1),mats.dark);roof.position.y=6.65;g.add(t,roof);g.position.set(x,0,z);g.scale.setScalar(s);scene.add(g)}
function buildPlayer(){player=new THREE.Group();const robe=new THREE.Mesh(new THREE.CylinderGeometry(.72,1.08,2.2,12),mats.dark);robe.position.y=1.08;player.add(robe);const belt=new THREE.Mesh(new THREE.TorusGeometry(.74,.12,8,24),mats.gold);belt.rotation.x=Math.PI/2;belt.position.y=1.56;player.add(belt);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.34,.42,.42,12),mats.skin);neck.position.y=2.26;player.add(neck);head=new THREE.Mesh(new THREE.SphereGeometry(1.2,34,26),mats.skin);head.scale.set(1,1.1,1.03);head.position.y=3.34;head.castShadow=true;player.add(head);const face=new THREE.MeshBasicMaterial({color:0x19050d});for(const x of[-.4,.4]){const e=new THREE.Mesh(new THREE.SphereGeometry(.1,10,8),face);e.scale.y=.65;e.position.set(x,3.44,1.1);player.add(e)}const nose=new THREE.Mesh(new THREE.ConeGeometry(.12,.42,12),mats.skin);nose.rotation.x=Math.PI/2;nose.position.set(0,3.2,1.2);player.add(nose);for(const x of[-.16,.16]){const m=new THREE.Mesh(new THREE.ConeGeometry(.12,.52,8),face);m.rotation.z=x<0?1.25:-1.25;m.position.set(x,2.96,1.06);player.add(m)}hairRoot=new THREE.Group();hairRoot.position.set(0,3.78,0);player.add(hairRoot);aura=new THREE.Mesh(new THREE.TorusGeometry(1.55,.06,8,64),new THREE.MeshBasicMaterial({color:0x5cf4ff,transparent:true,opacity:.45}));aura.rotation.x=Math.PI/2;aura.position.y=.08;player.add(aura);const glow=new THREE.PointLight(0xffe3a0,10,8,2);glow.position.set(0,4.1,.2);player.add(glow);player.position.set(0,0,4);scene.add(player);syncHair()}
function makeTuft(i){const g=new THREE.Group(),a=i/32*Math.PI*2,band=Math.floor(i/8),r=.25+band*.18,len=.65+band*.08,strand=new THREE.Mesh(new THREE.ConeGeometry(.09,len,7),mats.hair);strand.position.y=len*.34;strand.rotation.z=(Math.random()-.5)*.35;g.add(strand);g.position.set(Math.cos(a)*r,.2-band*.05,Math.sin(a)*r);g.rotation.y=-a;g.rotation.z=Math.sin(a)*.22;return g}
function syncHair(){const target=tuftCountForHair(state.hair);while(hairRoot.children.length<target)hairRoot.add(makeTuft(hairRoot.children.length));while(hairRoot.children.length>target)hairRoot.remove(hairRoot.children.at(-1));head.material.roughness=.14+state.hair*.0022;hairStageEl.textContent=hairStage(state.hair)}
function enemyMesh(type){const g=new THREE.Group();if(type==='wig'){const cap=new THREE.Mesh(new THREE.SphereGeometry(.8,16,10,0,Math.PI*2,0,Math.PI*.62),mats.hair);cap.position.y=1.15;g.add(cap);for(let i=0;i<12;i++){const a=i/12*Math.PI*2,s=new THREE.Mesh(new THREE.ConeGeometry(.14,.95,6),i%3===0?mats.pink:mats.hair);s.position.set(Math.cos(a)*.68,.64,Math.sin(a)*.68);s.rotation.z=Math.cos(a)*.3;s.rotation.x=Math.sin(a)*.3;g.add(s)}}else if(type==='toupee'){const base=new THREE.Mesh(new THREE.BoxGeometry(1.5,.3,.9),mats.hair);base.position.y=1.15;base.rotation.z=.14;g.add(base);for(let i=0;i<9;i++){const s=new THREE.Mesh(new THREE.ConeGeometry(.12,.8,6),mats.hair);s.position.set(-.58+i*.145,1.55,.05);s.rotation.z=-.2+i*.05;g.add(s)}const eye=new THREE.Mesh(new THREE.BoxGeometry(.72,.12,.06),mats.pink);eye.position.set(0,.9,.48);g.add(eye)}else if(type==='braid'){for(let i=0;i<7;i++){const b=new THREE.Mesh(new THREE.SphereGeometry(.32-i*.02,10,8),i%2?mats.pink:mats.hair);b.position.set(0,1.7-i*.42,0);g.add(b)}const crown=new THREE.Mesh(new THREE.TorusGeometry(.55,.13,8,24),mats.gold);crown.rotation.x=Math.PI/2;crown.position.y=1.9;g.add(crown)}else{const core=new THREE.Mesh(new THREE.SphereGeometry(2.1,24,18),mats.hair);core.position.y=3.4;g.add(core);for(let i=0;i<24;i++){const a=i/24*Math.PI*2,s=new THREE.Mesh(new THREE.ConeGeometry(.22,1.5,7),i%4===0?mats.gold:mats.hair);s.position.set(Math.cos(a)*1.6,3.2+Math.sin(i)*.5,Math.sin(a)*1.6);s.rotation.z=Math.cos(a)*.8;s.rotation.x=Math.sin(a)*.8;g.add(s)}}return g}
function spawn(type=null){if(!type){const r=Math.random();type=state.wave>=3&&r>.72?'braid':state.wave>=2&&r>.52?'toupee':'wig'}const cfg={wig:[22,1.5,8,.9,140],toupee:[38,1.85,12,1,240],braid:[58,1.15,15,1.05,360],boss:[700,.48,22,2.5,6000]}[type],mesh=enemyMesh(type),a=Math.random()*Math.PI*2,r=18.5+Math.random()*1.5;mesh.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(mesh);enemies.push({mesh,type,hp:cfg[0]+(type==='boss'?0:state.wave*3),speed:cfg[1],damage:cfg[2],radius:cfg[3],score:cfg[4],hitCd:0,phase:Math.random()*10,shoot:1,boss:type==='boss'})}
function spawnBoss(){state.boss=true;spawn('boss');announce('MEGA-PERRUQUE\nKAMI-KATSU',2300)}
function bind(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{input.keys[e.code]=true;if(e.code==='KeyE')bankai();if(e.code.startsWith('Shift'))dash()});addEventListener('keyup',e=>input.keys[e.code]=false);renderer.domElement.addEventListener('pointermove',e=>{input.pointer.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);raycaster.setFromCamera(input.pointer,camera);raycaster.ray.intersectPlane(groundPlane,input.aim)});renderer.domElement.addEventListener('pointerdown',()=>input.mouse=true);addEventListener('pointerup',()=>{input.mouse=false;input.touchFire=false});startBtn.onclick=startGame;restartBtn.onclick=startGame;setupJoy();$('#fireBtn').addEventListener('pointerdown',e=>{e.preventDefault();input.touchFire=true});$('#dashBtn').addEventListener('pointerdown',e=>{e.preventDefault();dash()});$('#superBtn').addEventListener('pointerdown',e=>{e.preventDefault();bankai()})}
function setupJoy(){const joy=$('#joy'),nub=$('#nub');let active=false,id=null;const move=e=>{const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy)||1,s=Math.min(max,l)/l;dx*=s;dy*=s;nub.style.transform=`translate(${dx}px,${dy}px)`;input.touchMove.set(dx/max,-dy/max)};joy.addEventListener('pointerdown',e=>{active=true;id=e.pointerId;joy.setPointerCapture(id);move(e)});joy.addEventListener('pointermove',e=>{if(active&&e.pointerId===id)move(e)});const end=()=>{active=false;input.touchMove.set(0,0);nub.style.transform='translate(0,0)'};joy.addEventListener('pointerup',end);joy.addEventListener('pointercancel',end)}
function startGame(){for(const list of[enemies,beams,particles,projectiles])for(const o of list)scene.remove(o.mesh||o);enemies=[];beams=[];particles=[];projectiles=[];state={score:0,hp:100,hair:0,wave:1,combo:1,comboTimer:0,elapsed:0,dashCd:0,invuln:0,boss:false};player.position.set(0,0,4);player.visible=true;syncHair();running=true;paused=false;spawnTimer=0;start.classList.remove('active');over.classList.remove('active');hud.style.display='block';announce('CALVITIE EN MODE COMBAT',1500);ensureAudio();for(let i=0;i<4;i++)spawn('wig')}
function gameOver(){running=false;player.visible=false;hud.style.display='none';$('#finalScore').textContent=`${Math.floor(state.score).toLocaleString('fr-FR')} points`;$('#endTitle').textContent=state.hair>=75?'CHEVELURE SAUVÉE':'ALOPÉCIE TOTALE';$('#epitaph').textContent=`Vincent termine avec ${Math.round(state.hair)} % de greffe. ${hairStage(state.hair)}.`;over.classList.add('active')}
function getMove(){let x=(input.keys.KeyD||input.keys.ArrowRight?1:0)-(input.keys.KeyA||input.keys.KeyQ||input.keys.ArrowLeft?1:0),z=(input.keys.KeyS||input.keys.ArrowDown?1:0)-(input.keys.KeyW||input.keys.KeyZ||input.keys.ArrowUp?1:0);x+=input.touchMove.x;z-=input.touchMove.y;const v=new THREE.Vector3(x,0,z);if(v.lengthSq()>1)v.normalize();return v}
function clampPlayer(){const r=Math.hypot(player.position.x,player.position.z);if(r>17.8){player.position.x*=17.8/r;player.position.z*=17.8/r}}
function nearest(){let b=null,d=Infinity;for(const e of enemies){const n=e.mesh.position.distanceToSquared(player.position);if(n<d){d=n;b=e}}return b}
function fire(){if(state.elapsed-lastFire<.13)return;lastFire=state.elapsed;const origin=player.position.clone().add(new THREE.Vector3(0,3.75,0));let target=input.aim.clone();if(input.touchFire||input.keys.Space||!Number.isFinite(target.x)){const n=nearest();target=n?n.mesh.position.clone().add(new THREE.Vector3(0,1,0)):player.position.clone().add(new THREE.Vector3(0,0,-10))}const dir=target.sub(origin).normalize(),len=25,mesh=new THREE.Mesh(new THREE.CylinderGeometry(.05,.12,len,7),new THREE.MeshBasicMaterial({color:state.hair>=100?0xffd166:0x5cf4ff,transparent:true,opacity:.9}));mesh.position.copy(origin).addScaledVector(dir,len/2);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);scene.add(mesh);beams.push({mesh,life:.09});let best=null,tBest=Infinity;for(const e of enemies){const to=e.mesh.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin),t=to.dot(dir);if(t<0||t>len)continue;const d=to.clone().addScaledVector(dir,-t).length();if(d<e.radius+.4&&t<tBest){best=e;tBest=t}}if(best)hit(best,11+state.combo*.45,dir);tone(520,.045,'square',.02)}
function hit(e,dmg,dir){e.hp-=dmg;e.mesh.position.addScaledVector(dir,.14);burst(e.mesh.position.clone().add(new THREE.Vector3(0,1,0)),0x5cf4ff,5);if(e.hp<=0)kill(e)}
function kill(e){const i=enemies.indexOf(e);if(i<0)return;enemies.splice(i,1);scene.remove(e.mesh);const prev=state.hair;state=applyKill(state,e.type,state.wave);state.comboTimer=3.2;syncHair();hairBurstToHead(e.mesh.position.clone(),state.hair-prev);burst(e.mesh.position.clone().add(new THREE.Vector3(0,1,0)),e.boss?0xffd166:0xff4fb3,e.boss?60:18);announce(e.boss?'GREFFE DIVINE TERMINÉE':`+${Math.round(state.hair-prev)} % DE CHEVEUX`,700)}
function damage(n){if(state.invuln>0)return;const before=state.hair;state=applyDamage(state,n);state.invuln=.38;state.combo=1;syncHair();shake=.7;flash.style.background='#ff174d';flash.style.opacity='.45';setTimeout(()=>flash.style.opacity='0',80);if(before>state.hair)announce(`-${Math.round(before-state.hair)} % : MÈCHES ARRACHÉES`,700);if(state.hp<=0)gameOver()}
function hairBurstToHead(pos,count){for(let i=0;i<Math.max(3,Math.round(count/2));i++){const m=new THREE.Mesh(new THREE.ConeGeometry(.05,.45,5),mats.hair);m.position.copy(pos).add(new THREE.Vector3(Math.random()-.5,1+Math.random(),Math.random()-.5));scene.add(m);particles.push({mesh:m,life:.7,vel:player.position.clone().add(new THREE.Vector3(0,3.8,0)).sub(m.position).multiplyScalar(2.1),implant:true})}}
function dash(){if(!running||state.dashCd>0)return;state.dashCd=2;state.invuln=.35;let v=getMove();if(v.lengthSq()<.1)v.set(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),player.rotation.y);player.position.addScaledVector(v.normalize(),4);clampPlayer();burst(player.position.clone().add(new THREE.Vector3(0,1,0)),0x5cf4ff,18)}
function bankai(){if(!running)return;const b=consumeBankai(state.hair);if(!b.activated)return;state.hair=b.hair;syncHair();announce('BANKAI CAPILLAIRE\nTEMPÊTE DE MÈCHES',1500);flash.style.opacity='.85';setTimeout(()=>flash.style.opacity='0',120);for(const e of[...enemies])if(e.mesh.position.distanceTo(player.position)<20)hit(e,e.boss?220:999,e.mesh.position.clone().sub(player.position).normalize());for(let i=0;i<90;i++)burst(player.position.clone().add(new THREE.Vector3(0,3.5,0)),0x2a0712,1)}
function update(dt){state.elapsed+=dt;state.dashCd=Math.max(0,state.dashCd-dt);state.invuln=Math.max(0,state.invuln-dt);state.comboTimer-=dt;if(state.comboTimer<=0)state.combo=1;const nw=1+Math.floor(state.elapsed/22);if(nw!==state.wave){state.wave=nw;announce(`VAGUE ${nw} : INVASION CAPILLAIRE`,1500)}if(state.wave>=4&&!state.boss)spawnBoss();player.position.addScaledVector(getMove(),5.7*dt);clampPlayer();let aim=input.aim.clone().sub(player.position);aim.y=0;if((input.touchFire||input.keys.Space)&&nearest())aim=nearest().mesh.position.clone().sub(player.position).setY(0);if(aim.lengthSq()>.1)player.rotation.y=Math.atan2(aim.x,aim.z);if(input.mouse||input.keys.Space||input.touchFire)fire();spawnTimer-=dt;if(spawnTimer<=0&&enemies.filter(e=>!e.boss).length<7+state.wave*2){spawn();spawnTimer=Math.max(.38,1.3-state.wave*.08)}for(const e of[...enemies]){e.phase+=dt;e.hitCd-=dt;const to=player.position.clone().sub(e.mesh.position);to.y=0;const d=to.length();to.normalize();e.mesh.position.addScaledVector(to,e.speed*dt);e.mesh.rotation.y=Math.atan2(to.x,to.z);e.mesh.position.y=e.boss?Math.sin(e.phase*1.3)*.2:Math.sin(e.phase*4)*.12;if(e.boss){e.shoot-=dt;if(e.shoot<=0){bossShot(e);e.shoot=1.15}}if(d<e.radius+1&&e.hitCd<=0){damage(e.damage);e.hitCd=.8}}for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.life-=dt;p.mesh.position.addScaledVector(p.vel,dt);if(p.mesh.position.distanceTo(player.position.clone().add(new THREE.Vector3(0,1,0)))<.8){damage(12);p.life=0}if(p.life<=0){scene.remove(p.mesh);projectiles.splice(i,1)}}for(let i=beams.length-1;i>=0;i--){const b=beams[i];b.life-=dt;b.mesh.material.opacity=Math.max(0,b.life/.09);if(b.life<=0){scene.remove(b.mesh);beams.splice(i,1)}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.mesh.position.addScaledVector(p.vel,dt);if(!p.implant)p.vel.y-=6*dt;p.mesh.material.opacity=clamp(p.life*2,0,1);if(p.life<=0){scene.remove(p.mesh);particles.splice(i,1)}}aura.rotation.z+=dt*2.4;aura.material.opacity=.35+Math.sin(state.elapsed*6)*.1+state.hair/300;updateHUD()}
function bossShot(e){const origin=e.mesh.position.clone().add(new THREE.Vector3(0,3.2,0));for(let k=-2;k<=2;k++){const dir=player.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),k*.16),mesh=new THREE.Mesh(new THREE.SphereGeometry(.24,9,7),new THREE.MeshBasicMaterial({color:0xff4fb3}));mesh.position.copy(origin);scene.add(mesh);projectiles.push({mesh,vel:dir.multiplyScalar(7),life:5})}}
function burst(pos,color,count=12){for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.TetrahedronGeometry(.06+Math.random()*.12),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1}));mesh.position.copy(pos);scene.add(mesh);particles.push({mesh,life:.35+Math.random()*.45,vel:new THREE.Vector3(Math.random()-.5,.2+Math.random(),Math.random()-.5).normalize().multiplyScalar(2+Math.random()*5)})}}
function updateHUD(){scoreEl.textContent=Math.floor(state.score).toLocaleString('fr-FR');waveEl.textContent=state.wave;comboEl.textContent=state.combo;hpFill.style.width=`${state.hp}%`;hairFill.style.width=`${state.hair}%`;hpText.textContent=Math.ceil(state.hp);hairText.textContent=Math.round(state.hair);hairStageEl.textContent=hairStage(state.hair);$('#superBtn').classList.toggle('ready',state.hair>=100)}
function announce(t,d=1100){announceEl.innerHTML=t.replace('\n','<br>');announceEl.classList.add('show');clearTimeout(msgTimer);msgTimer=setTimeout(()=>announceEl.classList.remove('show'),d)}
function ensureAudio(){if(audioCtx)return;try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch{}}
function tone(f,d=.1,type='sine',v=.03){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d+.02)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.035);if(running&&!paused)update(dt);const portrait=innerHeight>=innerWidth,base=portrait?new THREE.Vector3(0,21,18):new THREE.Vector3(0,18,23);if(shake>0){shake=Math.max(0,shake-dt*2);base.x+=(Math.random()-.5)*shake;base.y+=(Math.random()-.5)*shake*.4}camera.position.lerp(base,1-Math.exp(-8*dt));camera.lookAt(player&&player.visible?player.position.clone().multiplyScalar(.12).add(new THREE.Vector3(0,1.3,0)):new THREE.Vector3(0,1,0));renderer.render(scene,camera)}
try{init()}catch(err){console.error(err);loadingError.hidden=false;startBtn.disabled=true;startBtn.textContent='ERREUR 3D'}
