import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.min.js';
import { clamp, hairStage, applyDamage, applyKill, consumeBankai } from './game-core.js';
import { qualityForDevice } from './assets-core-v5.js';
import { createVincentModel } from './character-v5.js';
import { createHairEnemy } from './enemies-v5.js';

const $=s=>document.querySelector(s);
const ui={app:$('#app'),hud:$('#hud'),start:$('#start'),over:$('#gameover'),score:$('#score'),wave:$('#wave'),combo:$('#combo'),hpFill:$('#hpFill'),hairFill:$('#hairFill'),hpText:$('#hpText'),hairText:$('#hairText'),hairStage:$('#hairStage'),announce:$('#announcement'),flash:$('#flash'),startBtn:$('#startBtn'),restartBtn:$('#restartBtn'),error:$('#loadingError'),fire:$('#fireBtn'),dash:$('#dashBtn'),super:$('#superBtn'),joy:$('#joy'),nub:$('#nub')};
const quality=qualityForDevice({width:innerWidth,height:innerHeight,pixelRatio:devicePixelRatio});
const input={keys:{},pointer:new THREE.Vector2(),aim:new THREE.Vector3(0,0,-8),mouse:false,touchMove:new THREE.Vector2(),touchFire:false};
const cfg={wig:{hp:24,speed:1.55,damage:8,radius:.95},toupee:{hp:42,speed:1.85,damage:12,radius:1},braid:{hp:62,speed:1.15,damage:15,radius:1.08},boss:{hp:760,speed:.46,damage:22,radius:2.7}};
let scene,camera,renderer,clock,raycaster,plane,character,enemies=[],beams=[],particles=[],projectiles=[],implants=[],fallen=[],running=false,paused=false,spawnTimer=0,lastFire=0,msgTimer=0,shake=0,audioCtx=null;
let state={score:0,hp:100,hair:0,wave:1,combo:1,comboTimer:0,elapsed:0,dashCd:0,invuln:0,boss:false};

function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x08010e);scene.fog=new THREE.FogExp2(0x13031e,.028);camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,.1,150);camera.position.set(0,22.5,15.5);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(quality.pixelRatio);renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;ui.app.appendChild(renderer.domElement);clock=new THREE.Clock();raycaster=new THREE.Raycaster();plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);scene.add(new THREE.HemisphereLight(0xb7ecff,0x2a062d,1.65));const key=new THREE.DirectionalLight(0xffd3a2,3.25);key.position.set(-8,19,10);key.castShadow=true;key.shadow.mapSize.set(quality.shadows,quality.shadows);key.shadow.camera.left=-18;key.shadow.camera.right=18;key.shadow.camera.top=18;key.shadow.camera.bottom=-18;scene.add(key);const fill=new THREE.PointLight(0x5cf4ff,22,28,2);fill.position.set(-8,7,8);scene.add(fill);const rim=new THREE.PointLight(0xff4fb3,36,34,2);rim.position.set(10,9,-9);scene.add(rim);world();character=createVincentModel(THREE,{qualityFactor:quality.hairFactor});character.root.position.set(0,0,3.2);scene.add(character.root);bind();updateHUD();animate();window.__GAME_READY__=true}
function world(){const ground=new THREE.Mesh(new THREE.CircleGeometry(16.5,72),new THREE.MeshPhysicalMaterial({color:0x14051d,roughness:.68,metalness:.22,clearcoat:.08}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);for(let r=3;r<=15;r+=3){const ring=new THREE.Mesh(new THREE.TorusGeometry(r,.035,6,96),new THREE.MeshBasicMaterial({color:r%6===0?0xff4fb3:0x5cf4ff,transparent:true,opacity:.25,blending:THREE.AdditiveBlending}));ring.rotation.x=Math.PI/2;ring.position.y=.035;scene.add(ring)}const moon=new THREE.Mesh(new THREE.SphereGeometry(5.2,32,22),new THREE.MeshBasicMaterial({color:0xffefb2}));moon.position.set(-21,24,-48);scene.add(moon);for(let i=0;i<38;i++){const a=Math.random()*Math.PI*2,r=22+Math.random()*17,w=1.8+Math.random()*3,h=4+Math.random()*14,b=new THREE.Mesh(new THREE.BoxGeometry(w,h,w),new THREE.MeshStandardMaterial({color:[0x240632,0x0b1734,0x23103d][i%3],roughness:.82}));b.position.set(Math.cos(a)*r,h/2-1,Math.sin(a)*r);scene.add(b)}}
function reset(){for(const list of[enemies,beams,particles,projectiles,implants,fallen])for(const item of list)scene.remove(item.mesh||item);enemies=[];beams=[];particles=[];projectiles=[];implants=[];fallen=[];state={score:0,hp:100,hair:0,wave:1,combo:1,comboTimer:0,elapsed:0,dashCd:0,invuln:0,boss:false};character.root.position.set(0,0,3.2);character.root.visible=true;character.updateHair(0);spawnTimer=0;lastFire=0;updateHUD()}
function startGame(){reset();running=true;paused=false;ui.start.classList.remove('active');ui.over.classList.remove('active');ui.hud.style.display='block';ensureAudio();announce('CALVITIE EN MODE COMBAT',1400);for(let i=0;i<4;i++)spawn('wig')}
function spawn(type=null){if(!type){const r=Math.random();type=state.wave>=3&&r>.72?'braid':state.wave>=2&&r>.48?'toupee':'wig'}const c=cfg[type],mesh=createHairEnemy(THREE,type),a=Math.random()*Math.PI*2,r=13.7+Math.random()*1.4;mesh.position.set(Math.cos(a)*r,0,Math.sin(a)*r);scene.add(mesh);enemies.push({mesh,type,hp:c.hp+(type==='boss'?0:state.wave*3),speed:c.speed,damage:c.damage,radius:c.radius,hitCd:0,phase:Math.random()*10,shoot:1.2,boss:type==='boss'})}
function spawnBoss(){state.boss=true;spawn('boss');announce('MEGA-PERRUQUE\nKAMI-KATSU',2200)}
function moveVector(){let x=(input.keys.KeyD||input.keys.ArrowRight?1:0)-(input.keys.KeyA||input.keys.KeyQ||input.keys.ArrowLeft?1:0),z=(input.keys.KeyS||input.keys.ArrowDown?1:0)-(input.keys.KeyW||input.keys.KeyZ||input.keys.ArrowUp?1:0);x+=input.touchMove.x;z-=input.touchMove.y;const v=new THREE.Vector3(x,0,z);if(v.lengthSq()>1)v.normalize();return v}
function clampPlayer(){const r=Math.hypot(character.root.position.x,character.root.position.z);if(r>12.8){character.root.position.x*=12.8/r;character.root.position.z*=12.8/r}}
function nearest(){let best=null,d=Infinity;for(const e of enemies){const n=e.mesh.position.distanceToSquared(character.root.position);if(n<d){best=e;d=n}}return best}
function fire(){if(state.elapsed-lastFire<.125)return;lastFire=state.elapsed;const origin=character.root.position.clone().add(new THREE.Vector3(0,4.15,.48));let target=input.aim.clone();if(input.touchFire||input.keys.Space||!Number.isFinite(target.x)){const n=nearest();target=n?n.mesh.position.clone().add(new THREE.Vector3(0,n.boss?3:1,0)):character.root.position.clone().add(new THREE.Vector3(0,0,-10))}const dir=target.sub(origin).normalize(),len=22,beam=new THREE.Mesh(new THREE.CylinderGeometry(.045,.11,len,7),new THREE.MeshBasicMaterial({color:state.hair>=100?0xffd166:0x5cf4ff,transparent:true,opacity:.92,blending:THREE.AdditiveBlending}));beam.position.copy(origin).addScaledVector(dir,len/2);beam.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);scene.add(beam);beams.push({mesh:beam,life:.085});let hit=null,tMin=Infinity;for(const e of enemies){const to=e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?3:1,0)).sub(origin),t=to.dot(dir);if(t<0||t>len)continue;const lateral=to.clone().addScaledVector(dir,-t).length();if(lateral<e.radius+.45&&t<tMin){hit=e;tMin=t}}if(hit)damageEnemy(hit,11+state.combo*.6,dir);tone(540,.045,'square',.022)}
function damageEnemy(e,amount,dir){e.hp-=amount;e.mesh.position.addScaledVector(dir,.12);burst(e.mesh.position.clone().add(new THREE.Vector3(0,e.boss?3:1,0)),0x5cf4ff,5);if(e.hp<=0)kill(e)}
function kill(e){const index=enemies.indexOf(e);if(index<0)return;enemies.splice(index,1);const pos=e.mesh.position.clone();scene.remove(e.mesh);const before=state.hair;state=applyKill(state,e.type,state.wave);state.comboTimer=3.1;character.updateHair(state.hair);implantFlight(pos,state.hair-before,e.boss);burst(pos.clone().add(new THREE.Vector3(0,e.boss?2.8:1,0)),e.boss?0xffd166:0xff4fb3,e.boss?52:16);announce(e.boss?'GREFFE DIVINE\nHOMOLOGUÉE':`+${Math.round(state.hair-before)} % DE CHEVEUX`,e.boss?2500:700)}
function implantFlight(origin,gain,boss){const count=Math.max(2,Math.min(18,Math.round(gain*.9))),material=new THREE.MeshPhysicalMaterial({color:boss?0xffd166:0x2b1712,roughness:.42,clearcoat:.15});for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.ConeGeometry(.07,.55+Math.random()*.3,6),material);mesh.position.copy(origin).add(new THREE.Vector3((Math.random()-.5)*1.2,.6+Math.random()*1.4,(Math.random()-.5)*1.2));scene.add(mesh);implants.push({mesh,life:.8+Math.random()*.35,max:1.1})}}
function damagePlayer(amount){if(state.invuln>0)return;const before=state.hair;state=applyDamage(state,amount);state.combo=1;state.invuln=.42;character.updateHair(state.hair);const lost=Math.max(0,before-state.hair);detach(lost);shake=.75;ui.flash.style.background='#ff174d';ui.flash.style.opacity='.45';setTimeout(()=>ui.flash.style.opacity='0',90);announce(lost?`- ${lost} % DE GREFFE`:'CRÂNE IMPACTÉ',650);tone(95,.16,'square',.06);if(state.hp<=0)gameOver()}
function detach(loss){const count=Math.min(18,Math.max(3,Math.round(loss*.8))),material=new THREE.MeshStandardMaterial({color:0x2b1712,roughness:.68}),origin=character.root.position.clone().add(new THREE.Vector3(0,4.05,0));for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.ConeGeometry(.055,.48+Math.random()*.35,5),material);mesh.position.copy(origin);scene.add(mesh);fallen.push({mesh,life:.75+Math.random()*.45,velocity:new THREE.Vector3((Math.random()-.5)*5,2.5+Math.random()*3,(Math.random()-.5)*5),spin:Math.random()*8})}}
function dash(){if(!running||state.dashCd>0)return;state.dashCd=1.8;state.invuln=.32;let d=moveVector();if(d.lengthSq()<.1)d.set(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),character.root.rotation.y);character.root.position.addScaledVector(d.normalize(),3.5);clampPlayer();burst(character.root.position.clone().add(new THREE.Vector3(0,1,0)),0x5cf4ff,18);shake=.28}
function bankai(){if(!running)return;const result=consumeBankai(state.hair);if(!result.activated)return;state.hair=result.hair;character.updateHair(state.hair);announce('BANKAI CAPILLAIRE\nTEMPÊTE DE MÈCHES',1800);ui.flash.style.background='#fff7d0';ui.flash.style.opacity='.9';setTimeout(()=>ui.flash.style.opacity='0',120);for(const e of[...enemies])if(e.mesh.position.distanceTo(character.root.position)<15)damageEnemy(e,e.boss?210:999,e.mesh.position.clone().sub(character.root.position).normalize());shake=1.25;tone(65,.7,'sawtooth',.14)}
function gameOver(){running=false;character.root.visible=false;ui.hud.style.display='none';$('#finalScore').textContent=`${Math.floor(state.score).toLocaleString('fr-FR')} points`;$('#endTitle').textContent=state.hair>=75?'CHEVELURE SAUVÉE':'ALOPÉCIE TOTALE';$('#epitaph').textContent=`Greffe finale : ${Math.round(state.hair)} %. Diagnostic : ${hairStage(state.hair)}.`;ui.over.classList.add('active')}
function update(dt){state.elapsed+=dt;state.dashCd=Math.max(0,state.dashCd-dt);state.invuln=Math.max(0,state.invuln-dt);state.comboTimer-=dt;if(state.comboTimer<=0)state.combo=1;const wave=1+Math.floor(state.elapsed/21);if(wave!==state.wave){state.wave=wave;announce(`VAGUE ${wave} · INVASION CAPILLAIRE`,1500)}if(state.wave>=4&&!state.boss)spawnBoss();const move=moveVector();character.root.position.addScaledVector(move,5.25*dt);clampPlayer();character.animate(state.elapsed,move.length());let aim=input.aim.clone().sub(character.root.position);aim.y=0;if((input.touchFire||input.keys.Space)&&nearest())aim=nearest().mesh.position.clone().sub(character.root.position).setY(0);if(aim.lengthSq()>.1)character.root.rotation.y=Math.atan2(aim.x,aim.z);if(input.mouse||input.keys.Space||input.touchFire)fire();spawnTimer-=dt;if(spawnTimer<=0&&enemies.filter(e=>!e.boss).length<6+state.wave*2){spawn();spawnTimer=Math.max(.42,1.35-state.wave*.09)}for(const e of[...enemies]){e.phase+=dt;e.hitCd-=dt;const to=character.root.position.clone().sub(e.mesh.position);to.y=0;const distance=to.length();to.normalize();e.mesh.position.addScaledVector(to,e.speed*dt);e.mesh.rotation.y=Math.atan2(to.x,to.z);e.mesh.position.y=e.boss?Math.sin(e.phase*1.4)*.22:Math.sin(e.phase*4)*.1;e.mesh.rotation.z=Math.sin(e.phase*(e.boss?1.5:4.5))*(e.boss?.035:.09);if(e.boss){e.shoot-=dt;if(e.shoot<=0){shootBoss(e);e.shoot=1.22}}if(distance<e.radius+.95&&e.hitCd<=0){damagePlayer(e.damage);e.hitCd=.85}}effects(dt);updateHUD()}
function shootBoss(e){const origin=e.mesh.position.clone().add(new THREE.Vector3(0,3.4,0));for(let i=-2;i<=2;i++){const d=character.root.position.clone().add(new THREE.Vector3(0,1,0)).sub(origin).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),i*.14),mesh=new THREE.Mesh(new THREE.SphereGeometry(.22,10,8),new THREE.MeshBasicMaterial({color:0xff4fb3,blending:THREE.AdditiveBlending}));mesh.position.copy(origin);scene.add(mesh);projectiles.push({mesh,velocity:d.multiplyScalar(6.7),life:5})}}
function burst(pos,color,count=12){for(let i=0;i<count;i++){const mesh=new THREE.Mesh(new THREE.TetrahedronGeometry(.06+Math.random()*.11),new THREE.MeshBasicMaterial({color,transparent:true,opacity:1,blending:THREE.AdditiveBlending}));mesh.position.copy(pos);scene.add(mesh);particles.push({mesh,life:.35+Math.random()*.45,velocity:new THREE.Vector3(Math.random()-.5,Math.random()*1.1,Math.random()-.5).normalize().multiplyScalar(2+Math.random()*5)})}}
function effects(dt){for(let i=beams.length-1;i>=0;i--){const x=beams[i];x.life-=dt;x.mesh.material.opacity=Math.max(0,x.life/.085);if(x.life<=0){scene.remove(x.mesh);beams.splice(i,1)}}for(let i=particles.length-1;i>=0;i--){const x=particles[i];x.life-=dt;x.mesh.position.addScaledVector(x.velocity,dt);x.velocity.y-=6*dt;x.mesh.material.opacity=Math.max(0,x.life*2);if(x.life<=0){scene.remove(x.mesh);particles.splice(i,1)}}for(let i=projectiles.length-1;i>=0;i--){const x=projectiles[i];x.life-=dt;x.mesh.position.addScaledVector(x.velocity,dt);if(x.mesh.position.distanceTo(character.root.position.clone().add(new THREE.Vector3(0,1,0)))<.78){damagePlayer(12);x.life=0}if(x.life<=0){scene.remove(x.mesh);projectiles.splice(i,1)}}const target=character.root.position.clone().add(new THREE.Vector3(0,4.25,0));for(let i=implants.length-1;i>=0;i--){const x=implants[i];x.life-=dt;x.mesh.position.lerp(target,Math.min(1,dt*8));x.mesh.rotation.x+=dt*8;x.mesh.rotation.z+=dt*6;if(x.life<=0||x.mesh.position.distanceTo(target)<.3){scene.remove(x.mesh);implants.splice(i,1)}}for(let i=fallen.length-1;i>=0;i--){const x=fallen[i];x.life-=dt;x.mesh.position.addScaledVector(x.velocity,dt);x.velocity.y-=7*dt;x.mesh.rotation.z+=x.spin*dt;if(x.life<=0){scene.remove(x.mesh);fallen.splice(i,1)}}}
function updateHUD(){ui.score.textContent=Math.floor(state.score).toLocaleString('fr-FR');ui.wave.textContent=state.wave;ui.combo.textContent=state.combo;ui.hpFill.style.width=`${state.hp}%`;ui.hairFill.style.width=`${state.hair}%`;ui.hpText.textContent=Math.ceil(state.hp);ui.hairText.textContent=Math.floor(state.hair);ui.hairStage.textContent=hairStage(state.hair);ui.super.classList.toggle('ready',state.hair>=100)}
function announce(text,duration=1100){ui.announce.innerHTML=text.replace('\n','<br>');ui.announce.classList.add('show');clearTimeout(msgTimer);msgTimer=setTimeout(()=>ui.announce.classList.remove('show'),duration)}
function ensureAudio(){if(audioCtx)return;try{audioCtx=new(window.AudioContext||window.webkitAudioContext)()}catch{}}
function tone(f,d=.1,type='sine',vol=.03){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=f;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d+.02)}
function bind(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{input.keys[e.code]=true;if(e.code==='KeyE')bankai();if(e.code.startsWith('Shift'))dash();if(e.code==='Escape')paused=!paused});addEventListener('keyup',e=>input.keys[e.code]=false);renderer.domElement.addEventListener('pointermove',e=>{input.pointer.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight)*2+1);raycaster.setFromCamera(input.pointer,camera);raycaster.ray.intersectPlane(plane,input.aim)});renderer.domElement.addEventListener('pointerdown',()=>input.mouse=true);addEventListener('pointerup',()=>{input.mouse=false;input.touchFire=false});ui.startBtn.onclick=startGame;ui.restartBtn.onclick=startGame;ui.fire.addEventListener('pointerdown',e=>{e.preventDefault();input.touchFire=true});ui.dash.addEventListener('pointerdown',e=>{e.preventDefault();dash()});ui.super.addEventListener('pointerdown',e=>{e.preventDefault();bankai()});joystick()}
function joystick(){let active=false,id=null;const move=e=>{const r=ui.joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.34;let dx=e.clientX-cx,dy=e.clientY-cy,l=Math.hypot(dx,dy)||1,s=Math.min(max,l)/l;dx*=s;dy*=s;ui.nub.style.transform=`translate(${dx}px,${dy}px)`;input.touchMove.set(dx/max,-dy/max)};ui.joy.addEventListener('pointerdown',e=>{active=true;id=e.pointerId;ui.joy.setPointerCapture(id);move(e)});ui.joy.addEventListener('pointermove',e=>{if(active&&e.pointerId===id)move(e)});const end=()=>{active=false;input.touchMove.set(0,0);ui.nub.style.transform='translate(0,0)'};ui.joy.addEventListener('pointerup',end);ui.joy.addEventListener('pointercancel',end)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.035);if(running&&!paused)update(dt);const base=new THREE.Vector3(0,22.5,15.5);if(shake>0){shake=Math.max(0,shake-dt*1.9);base.x+=(Math.random()-.5)*shake;base.y+=(Math.random()-.5)*shake*.5}camera.position.lerp(base,1-Math.exp(-7*dt));camera.lookAt(character&&character.root.visible?character.root.position.clone().multiplyScalar(.15).add(new THREE.Vector3(0,1.4,-.6)):new THREE.Vector3(0,1.4,0));renderer.render(scene,camera)}
try{init()}catch(error){console.error(error);ui.error.hidden=false;ui.startBtn.disabled=true;ui.startBtn.textContent='ERREUR 3D — RECHARGER'}
